-- Remove a coluna legada `tasks.subtasks`.
--
-- Etapa 2 de 2 da migração de subtarefas embutidas para tarefas-filhas — a
-- etapa 1 (`20260813120000_migrate_subtasks_to_child_tasks.sql`) já converteu
-- os itens, então nada de dado vive mais aqui: o app não lê nem grava esta
-- coluna desde o deploy dessa mudança.
--
-- APLICADA em 2026-08-13 no projeto robwqxgllzxbxwnjkyic (produtividade),
-- como `drop_tasks_subtasks_column`. A condição para aplicar era não haver
-- mais cliente desatualizado gravando na coluna — um APK Android anterior ao
-- deploy continuaria enviando `subtasks` no upsert e, sem a coluna, o
-- PostgREST rejeitaria a escrita inteira. Conferido na hora: a escrita mais
-- recente numa tarefa com lista legada era de 2026-07-30, bem antes do
-- deploy, e as tarefas salvas no mesmo dia não trouxeram lista junto.
--
-- A consulta usada na conferência, para referência futura:
--
--   select max(updated_at)
--   from produtividade.tasks
--   where jsonb_typeof(subtasks) = 'array' and jsonb_array_length(subtasks) > 0;

alter table produtividade.tasks drop column subtasks;
